name: Build and Release

on:
  workflow_dispatch:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  release:
    runs-on: windows-latest

    steps:
      - name: Checkout del codice
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: "npm"

      - name: Installa le dipendenze
        run: npm install

      - name: Crea file cloudCredentials.ts
        shell: bash
        run: |
          cat <<EOF > src/main/ipc/cloudCredentials.ts
          export const GOOGLE_CLIENT_ID = "${{ secrets.GOOGLE_CLIENT_ID }}";
          export const GOOGLE_CLIENT_SECRET = "${{ secrets.GOOGLE_CLIENT_SECRET }}";
          export const GOOGLE_API_KEY = "${{ secrets.GOOGLE_API_KEY }}";
          export const MS_CLIENT_ID = "${{ secrets.MS_CLIENT_ID }}";
          export const PUSHER_KEY = "${{ secrets.PUSHER_KEY }}";
          export const PUSHER_CLUSTER = "${{ secrets.PUSHER_CLUSTER }}";
          export const PUSHER_WEBHOOK = "${{ secrets.PUSHER_WEBHOOK }}";
          export const HUB_URL = "${{ secrets.HUB_URL }}";
          export const HUB_CREATE_SECRET = "${{ secrets.HUB_CREATE_SECRET }}";
          EOF

      - name: Costruisci e pubblica la Release
        run: npm run publish-app
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
